version: '3.8'
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gymtracker
      MYSQL_USER: dad
      MYSQL_PASSWORD: padre
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8081:8081"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/gymtracker
      SPRING_DATASOURCE_USERNAME: dad
      SPRING_DATASOURCE_PASSWORD: padre
      SERVER_PORT: 443
    ports:
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

