
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('sentadillas', 'cuadriceps, gluteos', 'ejercicio para piernas y gluteos', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('dominadas', 'espalda, biceps', 'ejercicio para la espalda y biceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('peso muerto', 'espalda baja, isquiotibiales, gluteos', 'ejercicio compuesto para la espalda baja, gluteos y piernas', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('fondos en paralelas', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('remo con barra', 'espalda, biceps', 'ejercicio para la espalda y biceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('flexiones de brazos', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('curl de biceps con barra', 'biceps', 'ejercicio para el desarrollo de los biceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones laterales', 'deltoides', 'ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('zancadas', 'cuadriceps, gluteos', 'ejercicio para piernas y gluteos', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press militar', 'deltoides', 'ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('abdominales', 'abdominales', 'ejercicio para el fortalecimiento del abdomen', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('prensa de piernas', 'cuadriceps, isquiotibiales, gluteos', 'ejercicio para piernas y gluteos', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('extensiones de triceps en polea alta', 'triceps', 'ejercicio para el triceps', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('curl de biceps con mancuernas', 'biceps', 'ejercicio para el desarrollo de los biceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('hip thrust', 'gluteos', 'ejercicio para gluteos y parte baja de la espalda', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones de talones', 'gemelos', 'ejercicio para los musculos de la pantorrilla', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('pull-ups', 'espalda, biceps', 'ejercicio para la espalda y biceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de hombros con mancuernas', 'deltoides', 'ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('deadlift rumano', 'espalda baja, isquiotibiales, gluteos', 'ejercicio para la parte posterior del cuerpo', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('burpees', 'multiples', 'ejercicio cardiovascular y de fuerza', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca inclinado', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('fondos en anillas', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('pajaros', 'deltoides', 'ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('sentadillas frontales', 'cuadriceps, gluteos', 'ejercicio para piernas y gluteos', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca declinado', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('curl de biceps en polea baja', 'biceps', 'ejercicio para el desarrollo de los biceps', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de hombros con barra', 'deltoides', 'ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('desplantes', 'cuadriceps, gluteos', 'ejercicio para piernas y gluteos', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('pull-overs', 'pectorales, espalda, triceps', 'ejercicio para el pecho, espalda y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('hip thrust en banco', 'gluteos', 'ejercicio para gluteos y parte baja de la espalda', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('extensiones de triceps con mancuerna', 'triceps', 'ejercicio para el triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('flexiones diamante', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones frontales con mancuernas', 'deltoides', 'ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('zancadas inversas', 'cuadriceps, gluteos', 'ejercicio para piernas y gluteos', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('dominadas en agarre cerrado', 'espalda, biceps', 'ejercicio para la espalda y biceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca con mancuernas', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('face pull', 'deltoides, trapecio', 'ejercicio para el desarrollo de los hombros y trapecio', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('peso muerto rumano con mancuernas', 'espalda baja, isquiotibiales, gluteos', 'ejercicio para la parte posterior del cuerpo', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('abdominales en polea alta', 'abdominales', 'ejercicio para el fortalecimiento del abdomen', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('sentadillas bulgaras', 'cuadriceps, gluteos', 'ejercicio para piernas y gluteos', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca con agarre cerrado', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('pulldown con polea alta', 'espalda, biceps', 'ejercicio para la espalda y biceps', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de hombros con mancuernas sentado', 'deltoides', 'ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('desplantes con salto', 'cuadriceps, gluteos', 'ejercicio para piernas y gluteos', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('curl de martillo con mancuernas', 'biceps, antebrazo', 'ejercicio para el desarrollo de los biceps y antebrazos', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones laterales con polea baja', 'deltoides', 'ejercicio para el desarrollo de los hombros', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones de gemelos sentado', 'gemelos', 'ejercicio para los musculos de la pantorrilla', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('chin-ups', 'espalda, biceps', 'ejercicio para la espalda y biceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('flexiones en escalera', 'pectorales, triceps', 'ejercicio para el pecho y triceps', 'peso corporal');
