INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('sentadilla con barra', 'cuadriceps, gluteos', 'Ejercicio para piernas y gluteos', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('dominadas', 'espalda, biceps', 'Ejercicio para la espalda y biceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('peso muerto', 'espalda baja, isquiotibiales, gluteos', 'Ejercicio para la espalda baja, gluteos y piernas', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('fondos en paralelas', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('remo con barra', 'espalda, biceps', 'Ejercicio para la espalda y biceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('flexiones de brazos', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('curl de biceps con barra', 'biceps', 'Ejercicio para el desarrollo de los biceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones laterales', 'deltoides', 'Ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('zancadas', 'cuadriceps, gluteos', 'Ejercicio para piernas y gluteos', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press militar', 'deltoides', 'Ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('abdominales', 'abdominales', 'Ejercicio para el fortalecimiento del abdomen', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('prensa de piernas', 'cuadriceps, isquiotibiales, gluteos', 'Ejercicio para piernas y gluteos', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('extensiones de triceps en polea alta', 'triceps', 'Ejercicio para el triceps', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('curl de biceps con mancuernas', 'biceps', 'Ejercicio para el desarrollo de los biceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('hip thrust', 'gluteos', 'Ejercicio para gluteos y parte baja de la espalda', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones de talones', 'gemelos', 'Ejercicio para los musculos de la pantorrilla', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('hiperextensiones', 'espalda baja, isquiotibiales, gluteos', 'Ejercicio para la parte posterior del cuerpo', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de hombros con mancuernas', 'deltoides', 'Ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('sentadilla', 'cuadriceps, gluteos', 'Ejercicio para piernas y gluteos', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('burpees', 'multiples', 'Ejercicio cardiovascular y de fuerza', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca inclinado', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('flexiones en pica', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('pajaros', 'deltoides', 'Ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('sentadillas frontales', 'cuadriceps, gluteos', 'Ejercicio para piernas y gluteos', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca declinado', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('curl de biceps en polea baja', 'biceps', 'Ejercicio para el desarrollo de los biceps', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de hombros con barra', 'deltoides', 'Ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('sentadilla pistola', 'cuadriceps, gluteos', 'Ejercicio para piernas y gluteos', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('pullover', 'pectorales, espalda, triceps', 'Ejercicio para el pecho, espalda y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('hip thrust en banco', 'gluteos', 'Ejercicio para gluteos y parte baja de la espalda', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('extensiones de triceps con mancuerna', 'triceps', 'Ejercicio para el triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('flexiones diamante', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones frontales con mancuernas', 'deltoides', 'Ejercicio para el desarrollo de los hombros', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('zancadas inversas', 'cuadriceps, gluteos', 'Ejercicio para piernas y gluteos', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('dominadas australianas', 'espalda, biceps', 'Ejercicio para la espalda y biceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca con mancuernas', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('face pull', 'deltoides, trapecio', 'Ejercicio para el desarrollo de los hombros y trapecio', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('peso muerto rumano con mancuernas', 'espalda baja, isquiotibiales, gluteos', 'Ejercicio para la parte posterior del cuerpo', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('abdominales en polea alta', 'abdominales', 'Ejercicio para el fortalecimiento del abdomen', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('sentadillas bulgaras', 'cuadriceps, gluteos', 'Ejercicio para piernas y gluteos', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('press de banca con agarre cerrado', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('pullover en maquina', 'espalda, biceps', 'Ejercicio para la espalda y biceps', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('remo con mancuerna', 'espalda', 'Ejercicio para el desarrollo de la espalda', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('curl predicator', 'biceps', 'Ejercicio para el desarrollo del biceps en máquina', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('cossack squat', 'cuadriceps, gluteos', 'Ejercicio para piernas y gluteos', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('curl de martillo con mancuernas', 'biceps, antebrazo', 'Ejercicio para biceps y antebrazos', 'pesas');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones laterales con polea baja', 'deltoides', 'Ejercicio para el desarrollo de los hombros', 'polea');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('elevaciones de gemelos sentado', 'gemelos', 'Ejercicio para los musculos de la pantorrilla', 'maquina');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('dominadas agarre neutro', 'espalda, biceps', 'Ejercicio para la espalda y biceps', 'peso corporal');
INSERT INTO ejercicioORM (nombre, musculo, descripcion, equipamiento) VALUES ('flexiones inclinadas', 'pectorales, triceps', 'Ejercicio para el pecho y triceps', 'peso corporal');
